use truce::prelude::*;
use truce_gui::IntoLayoutEditor;
use truce_gui_types::layout::{GridLayout, knob, widgets};

// --- Parameters ---

use TransposeParamsParamId as P;
use std::sync::Arc;

#[derive(Params)]
pub struct TransposeParams {
    #[param(
        name = "Semitones",
        short_name = "Semi",
        range = "discrete(-12, 12)",
        unit = "st"
    )]
    pub semitones: IntParam,

    #[param(name = "Octave", short_name = "Oct", range = "discrete(-3, 3)")]
    pub octave: IntParam,
}

// new() and Default are generated by #[derive(Params)] + #[param(...)]

// --- Plugin ---

pub struct Transpose {
    pub params: Arc<TransposeParams>,
    /// Maps input note -> output note that was actually sent.
    /// Used to send correct `NoteOff` even if shift changes mid-hold.
    active_notes: [Option<u8>; 128],
}

impl Transpose {
    pub fn new(params: Arc<TransposeParams>) -> Self {
        Self {
            params,
            active_notes: [None; 128],
        }
    }
}

/// Apply `shift` to a MIDI `note` and clamp the result to `0..=127`.
/// Centralizes the widening (`u8 → i32` for the signed math) and the
/// final narrow back to `u8`.
#[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
fn shift_midi(note: u8, shift: i32) -> u8 {
    (i32::from(note) + shift).clamp(0, 127) as u8
}

impl PluginLogic for Transpose {
    type Params = TransposeParams;

    /// MIDI effect: no audio I/O. CLAP/VST3/AU(aumi)/LV2 honor this;
    /// AAX (which has no audio-less plugin category) auto-adds a
    /// stereo passthrough inside `truce-aax` so the DAW's track
    /// audio flows through unchanged.
    fn bus_layouts() -> Vec<BusLayout> {
        vec![BusLayout::new()]
    }

    fn reset(&mut self, sample_rate: f64, _max_block_size: usize) {
        self.params.set_sample_rate(sample_rate);
        self.params.snap_smoothers();
    }

    fn process(
        &mut self,
        _buffer: &mut AudioBuffer,
        events: &EventList,
        context: &mut ProcessContext,
    ) -> ProcessStatus {
        let semitones = self.params.semitones.value_i32();
        let octave = self.params.octave.value_i32();
        let shift = semitones + octave * 12;

        for event in events.iter() {
            match &event.body {
                EventBody::NoteOn {
                    group,
                    channel,
                    note,
                    velocity,
                } => {
                    let transposed = shift_midi(*note, shift);
                    self.active_notes[*note as usize] = Some(transposed);
                    context.output_events.push(Event::new(
                        event.sample_offset,
                        EventBody::NoteOn {
                            group: *group,
                            channel: *channel,
                            note: transposed,
                            velocity: *velocity,
                        },
                    ));
                }
                EventBody::NoteOff {
                    group,
                    channel,
                    note,
                    velocity,
                } => {
                    // Use the pitch that was actually sent, not the
                    // current shift - held notes get a matching off
                    // even after the user re-transposes mid-hold.
                    let output_note = self.active_notes[*note as usize]
                        .take()
                        .unwrap_or_else(|| shift_midi(*note, shift));
                    context.output_events.push(Event::new(
                        event.sample_offset,
                        EventBody::NoteOff {
                            group: *group,
                            channel: *channel,
                            note: output_note,
                            velocity: *velocity,
                        },
                    ));
                }
                _ => {}
            }
        }

        ProcessStatus::Normal
    }

    fn editor(params: Arc<TransposeParams>) -> Box<dyn Editor> {
        GridLayout::build(vec![widgets(vec![
            knob(P::Semitones, "Semitones"),
            knob(P::Octave, "Octave"),
        ])])
        .with_title("TRANSPOSE")
        .into_editor(&params)
    }
}

truce::plugin! {
    logic: Transpose,
    params: TransposeParams,
}

truce::enable_rt_paranoid!();

// --- Tests ---

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn process_is_allocation_free() {
        use std::time::Duration;
        use truce_test::{InputSource, assert_no_audio_alloc, driver};
        assert_no_audio_alloc(|| {
            driver!(Plugin)
                .duration(Duration::from_millis(40))
                .input(InputSource::Constant(0.25))
                .script(|s| {
                    s.note_on(60, 0.8);
                    s.set_param(P::Semitones, 0.9);
                    s.wait_ms(15);
                    s.set_param(P::Semitones, 0.1);
                    s.wait_ms(15);
                    s.note_off(60);
                })
                .run()
        });
    }

    #[test]
    fn transpose_up_octave() {
        let params = Arc::new(TransposeParams::new());
        let mut plugin = Transpose::new(Arc::clone(&params));
        plugin.params.octave.set_value(1);
        plugin.reset(44100.0, 512);

        let input = vec![vec![0.0f32; 512]; 2];
        let input_refs: Vec<&[f32]> = input.iter().map(std::vec::Vec::as_slice).collect();
        let mut output = vec![vec![0.0f32; 512]; 2];
        let mut output_refs: Vec<&mut [f32]> =
            output.iter_mut().map(std::vec::Vec::as_mut_slice).collect();

        let mut buffer = unsafe { AudioBuffer::from_slices(&input_refs, &mut output_refs, 512) };

        let mut events = EventList::default();
        events.push(Event::new(
            0,
            EventBody::NoteOn {
                group: 0,
                channel: 0,
                note: 60,
                velocity: 102,
            },
        ));

        let transport = TransportInfo::default();
        let mut output_events = EventList::default();
        let mut context = ProcessContext::new(&transport, 44100.0, 512, &mut output_events);

        plugin.process(&mut buffer, &events, &mut context);

        assert_eq!(output_events.len(), 1);
        match &output_events.get(0).unwrap().body {
            EventBody::NoteOn { note, .. } => assert_eq!(*note, 72), // C4 + 12 = C5
            _ => panic!("Expected NoteOn"),
        }
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn gui_screenshot_macos() {
        truce_test::screenshot!(Plugin, "screenshots/transpose_default_macos.png").run();
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn gui_screenshot_linux() {
        truce_test::screenshot!(Plugin, "screenshots/transpose_default_linux.png")
            .pixel_threshold(2)
            .run();
    }

    #[cfg(target_os = "windows")]
    #[test]
    fn gui_screenshot_windows() {
        truce_test::screenshot!(Plugin, "screenshots/transpose_default_windows.png")
            .pixel_threshold(2)
            .run();
    }

    /// Regression guard: see `arpeggio/src/lib.rs::tests::category_is_note_effect`.
    #[test]
    fn category_is_note_effect() {
        use truce_core::info::PluginCategory;
        use truce_core::plugin::PluginRuntime;
        assert_eq!(
            <Plugin as PluginRuntime>::info().category,
            PluginCategory::NoteEffect
        );
    }
}
