/**
 * Truce AU v3 shim.
 *
 * Implements an AUAudioUnit subclass that calls back into Rust for all
 * plugin logic (processing, parameters, state).
 *
 * The Rust side registers a plugin descriptor and callbacks via
 * truce_au_register(). The class name is unique per plugin binary
 * (set via -DTRUCE_AU_CLASS_NAME in build.rs) to avoid ObjC class
 * collisions when multiple truce AU plugins are loaded in the same process.
 */

@import AudioToolbox;
@import AVFAudio;
@import Foundation;

// Fallback class name if not set by build.rs (shouldn't happen in practice).
#ifndef TRUCE_AU_CLASS_NAME
#define TRUCE_AU_CLASS_NAME TruceAUBase
#endif

// Rust-side init function — generated by export_au! macro.
#include "au_shim_types.h"

// Globals defined in au_shim_common.c

// ---------------------------------------------------------------------------
// AUAudioUnit subclass (unique name per plugin binary)
// ---------------------------------------------------------------------------

@interface TRUCE_AU_CLASS_NAME : AUAudioUnit {
@public
    void *_rustCtx;
    AUAudioUnitBusArray *_inputBusArray;
    AUAudioUnitBusArray *_outputBusArray;
    AUParameterTree *_parameterTree;
    NSArray<AUParameter *> *_parameterList;
    double _sampleRate;
    uint32_t _maxFrames;
}
@end

@implementation TRUCE_AU_CLASS_NAME

// registerSubclass is available via truce_au_v3_register_subclass() below
// but currently DISABLED — dual registration (plist + registerSubclass)
// may cause AudioComponentCopyConfigurationInfo to hang.

- (instancetype)initWithComponentDescription:(AudioComponentDescription)componentDescription
                                     options:(AudioComponentInstantiationOptions)options
                                       error:(NSError **)outError {
    self = [super initWithComponentDescription:componentDescription
                                       options:options
                                         error:outError];
    if (!self) {
        fprintf(stderr, "[truce-au-v3] super init FAILED: %s\n",
                outError && *outError ? (*outError).localizedDescription.UTF8String : "nil");
        return nil;
    }
    if (!g_callbacks) return self;

    _rustCtx = g_callbacks->create();
    _sampleRate = 44100.0;
    _maxFrames = 1024;

    // Audio buses
    // Always create a stereo input bus — instruments need a dummy bus so
    // Apple's v3→v2 bridge can query it without crashing (-10863).
    // The render block uses g_descriptor->num_inputs to decide whether to
    // actually pull input, so the dummy bus is never read for instruments.
    AVAudioFormat *defaultFormat = [[AVAudioFormat alloc]
        initStandardFormatWithSampleRate:44100.0
                                channels:g_descriptor->num_outputs];

    uint32_t inputCh = g_descriptor->num_inputs > 0 ? g_descriptor->num_inputs : g_descriptor->num_outputs;
    AVAudioFormat *inputFormat = [[AVAudioFormat alloc]
        initStandardFormatWithSampleRate:44100.0
                                channels:inputCh];
    AUAudioUnitBus *inputBus = [[AUAudioUnitBus alloc]
        initWithFormat:inputFormat error:outError];
    _inputBusArray = [[AUAudioUnitBusArray alloc]
        initWithAudioUnit:self busType:AUAudioUnitBusTypeInput
                   busses:inputBus ? @[inputBus] : @[]];

    AUAudioUnitBus *outputBus = [[AUAudioUnitBus alloc]
        initWithFormat:defaultFormat error:outError];
    _outputBusArray = [[AUAudioUnitBusArray alloc]
        initWithAudioUnit:self busType:AUAudioUnitBusTypeOutput
                   busses:outputBus ? @[outputBus] : @[]];

    [self buildParameterTree];
    return self;
}

- (void)dealloc {
    if (_rustCtx && g_callbacks) {
        g_callbacks->destroy(_rustCtx);
        _rustCtx = NULL;
    }
}

- (AUAudioUnitBusArray *)inputBusses { return _inputBusArray; }
- (AUAudioUnitBusArray *)outputBusses { return _outputBusArray; }

- (void)buildParameterTree {
    if (!g_callbacks || !_rustCtx) return;

    NSMutableArray<AUParameter *> *params = [NSMutableArray new];
    NSMutableDictionary<NSString *, NSMutableArray<AUParameter *> *> *groups = [NSMutableDictionary new];

    for (uint32_t i = 0; i < g_num_params; i++) {
        const AuParamDescriptor *desc = &g_param_descriptors[i];

        AudioUnitParameterOptions flags =
            kAudioUnitParameterFlag_IsWritable |
            kAudioUnitParameterFlag_IsReadable;

        AUParameter *param = [AUParameterTree
            createParameterWithIdentifier:[NSString stringWithFormat:@"param%u", desc->id]
                                     name:[NSString stringWithUTF8String:desc->name]
                                  address:desc->id
                                      min:(AUValue)desc->min
                                      max:(AUValue)desc->max
                                     unit:kAudioUnitParameterUnit_Generic
                                 unitName:nil
                                    flags:flags
                             valueStrings:nil
                      dependentParameters:nil];
        param.value = (AUValue)desc->default_value;

        NSString *groupName = [NSString stringWithUTF8String:desc->group];
        if (groupName.length > 0) {
            if (!groups[groupName]) groups[groupName] = [NSMutableArray new];
            [groups[groupName] addObject:param];
        } else {
            [params addObject:param];
        }
    }

    NSMutableArray *children = [NSMutableArray arrayWithArray:params];
    for (NSString *groupName in groups) {
        AUParameterGroup *group = [AUParameterTree
            createGroupWithIdentifier:groupName name:groupName
                             children:groups[groupName]];
        [children addObject:group];
    }

    _parameterTree = [AUParameterTree createTreeWithChildren:children];
    _parameterList = [_parameterTree.allParameters copy];

    __unsafe_unretained TRUCE_AU_CLASS_NAME *weakSelf = self;

    _parameterTree.implementorValueObserver = ^(AUParameter *p, AUValue v) {
        if (weakSelf && g_callbacks)
            g_callbacks->param_set_value(weakSelf->_rustCtx, (uint32_t)p.address, (double)v);
    };

    _parameterTree.implementorValueProvider = ^AUValue(AUParameter *p) {
        if (weakSelf && g_callbacks)
            return (AUValue)g_callbacks->param_get_value(weakSelf->_rustCtx, (uint32_t)p.address);
        return 0.0;
    };

    _parameterTree.implementorStringFromValueCallback = ^NSString *(AUParameter *p, const AUValue *v) {
        if (weakSelf && g_callbacks) {
            AUValue val = v ? *v : p.value;
            char buf[128];
            uint32_t len = g_callbacks->param_format_value(
                weakSelf->_rustCtx, (uint32_t)p.address, (double)val, buf, sizeof(buf));
            if (len > 0)
                return [[NSString alloc] initWithBytes:buf length:len encoding:NSUTF8StringEncoding];
        }
        return [NSString stringWithFormat:@"%.2f", v ? *v : p.value];
    };
}

- (AUParameterTree *)parameterTree { return _parameterTree; }

- (BOOL)allocateRenderResourcesAndReturnError:(NSError **)outError {
    if (![super allocateRenderResourcesAndReturnError:outError]) return NO;

    if (_outputBusArray.count > 0)
        _sampleRate = _outputBusArray[0].format.sampleRate;
    _maxFrames = self.maximumFramesToRender;

    if (g_callbacks && _rustCtx)
        g_callbacks->reset(_rustCtx, _sampleRate, _maxFrames);

    return YES;
}

- (void)deallocateRenderResources {
    [super deallocateRenderResources];
}

- (AUInternalRenderBlock)internalRenderBlock {
    void *ctx = _rustCtx;
    const AuCallbacks *callbacks = g_callbacks;
    uint32_t numIn = g_descriptor ? g_descriptor->num_inputs : 0;
    uint32_t numOut = g_descriptor ? g_descriptor->num_outputs : 2;

    return ^AUAudioUnitStatus(
        AudioUnitRenderActionFlags *flags,
        const AudioTimeStamp *timestamp,
        AUAudioFrameCount frameCount,
        NSInteger busNumber,
        AudioBufferList *outputData,
        const AURenderEvent *eventHead,
        AURenderPullInputBlock __unsafe_unretained pullInput
    ) {
        (void)flags; (void)busNumber;
        if (!callbacks || !ctx) return kAudioUnitErr_Uninitialized;

        // Pull input for effects
        if (numIn > 0 && pullInput) {
            AudioUnitRenderActionFlags pullFlags = 0;
            AUAudioUnitStatus s = pullInput(&pullFlags, timestamp, frameCount, 0, outputData);
            if (s != noErr) return s;
        }

        // Collect MIDI and parameter events
        AuMidiEvent midiEvents[256];
        uint32_t numMidi = 0;
        const AURenderEvent *ev = eventHead;
        while (ev && numMidi < 256) {
            if (ev->head.eventType == AURenderEventMIDI) {
                const AUMIDIEvent *m = &ev->MIDI;
                midiEvents[numMidi].sample_offset = (uint32_t)m->eventSampleTime;
                midiEvents[numMidi].status = m->data[0];
                midiEvents[numMidi].data1 = m->length > 1 ? m->data[1] : 0;
                midiEvents[numMidi].data2 = m->length > 2 ? m->data[2] : 0;
                midiEvents[numMidi]._pad = 0;
                numMidi++;
            } else if (ev->head.eventType == AURenderEventParameter ||
                       ev->head.eventType == AURenderEventParameterRamp) {
                callbacks->param_set_value(ctx,
                    (uint32_t)ev->parameter.parameterAddress,
                    (double)ev->parameter.value);
            }
            ev = ev->head.next;
        }

        const float *inPtrs[32];
        float *outPtrs[32];
        for (uint32_t c = 0; c < numIn && c < outputData->mNumberBuffers; c++)
            inPtrs[c] = (const float *)outputData->mBuffers[c].mData;
        for (uint32_t c = 0; c < numOut && c < outputData->mNumberBuffers; c++)
            outPtrs[c] = (float *)outputData->mBuffers[c].mData;

        callbacks->process(ctx, inPtrs, outPtrs, numIn, numOut,
                          (uint32_t)frameCount, midiEvents, numMidi);
        return noErr;
    };
}

- (NSDictionary *)fullState {
    NSMutableDictionary *s = [[super fullState] mutableCopy] ?: [NSMutableDictionary new];
    if (g_callbacks && _rustCtx) {
        uint8_t *data = NULL; uint32_t len = 0;
        g_callbacks->state_save(_rustCtx, &data, &len);
        if (data && len > 0) {
            s[@"truce_state"] = [NSData dataWithBytes:data length:len];
            g_callbacks->state_free(data, len);
        }
    }
    return s;
}

- (void)setFullState:(NSDictionary *)fullState {
    [super setFullState:fullState];
    NSData *blob = fullState[@"truce_state"];
    if (blob && g_callbacks && _rustCtx) {
        g_callbacks->state_load(_rustCtx, blob.bytes, (uint32_t)blob.length);
        for (AUParameter *p in _parameterList)
            p.value = (AUValue)g_callbacks->param_get_value(_rustCtx, (uint32_t)p.address);
    }
}

- (NSArray<NSNumber *> *)channelCapabilities {
    if (g_descriptor->num_inputs == 0)
        return @[@0, @(g_descriptor->num_outputs)];
    return @[@(g_descriptor->num_inputs), @(g_descriptor->num_outputs)];
}

- (BOOL)canProcessInPlace { return (g_descriptor->num_inputs > 0); }
- (NSTimeInterval)latency { return 0.0; }
- (NSTimeInterval)tailTime { return 0.0; }
- (BOOL)shouldBypassEffect { return NO; }
- (void)setShouldBypassEffect:(BOOL)value { (void)value; }
- (BOOL)supportsUserPresets { return NO; }

// For instruments: support MIDI input
- (BOOL)isMusicDeviceOrEffect {
    return YES;
}

@end

// ---------------------------------------------------------------------------
// AUAudioUnitFactory — NSExtensionPrincipalClass for v3 appex.
//
// The extension system calls [factory init] then createAudioUnitWithComponentDescription:error:.
// We create our AUAudioUnit subclass from the factory.
// Class name set via -DTRUCE_AU_FACTORY_CLASS_NAME in build.rs.
// ---------------------------------------------------------------------------

@interface TRUCE_AU_FACTORY_CLASS_NAME : NSObject <AUAudioUnitFactory>
@end

@implementation TRUCE_AU_FACTORY_CLASS_NAME

- (nullable AUAudioUnit *)createAudioUnitWithComponentDescription:(AudioComponentDescription)desc
                                                            error:(NSError **)error {
    return [[TRUCE_AU_CLASS_NAME alloc] initWithComponentDescription:desc options:0 error:error];
}

- (void)beginRequestWithExtensionContext:(NSExtensionContext *)context {
    // Complete the request immediately. If left incomplete, callers like
    // AudioComponentCopyConfigurationInfo hang waiting for a response.
    [context completeRequestReturningItems:@[] completionHandler:nil];
}

@end

// ---------------------------------------------------------------------------
// Called by the constructor in au_shim_common.c after globals are populated.
// Registers the AUAudioUnit subclass so the v3→v2 bridge can find it.
// This is needed for AudioComponentCopyConfigurationInfo (GarageBand scanning)
// and AudioComponentInstanceNew (auval, AULab).
// ---------------------------------------------------------------------------

void truce_au_v3_register_subclass(void) {
    if (!g_descriptor) return;

    AudioComponentDescription desc = {
        .componentType = FOURCC(g_descriptor->component_type),
        .componentSubType = FOURCC(g_descriptor->component_subtype),
        .componentManufacturer = FOURCC(g_descriptor->component_manufacturer),
        .componentFlags = 0,
        .componentFlagsMask = 0
    };
    NSString *name = [NSString stringWithFormat:@"Truce: %s", g_descriptor->name];

    [TRUCE_AU_CLASS_NAME registerSubclass:[TRUCE_AU_CLASS_NAME class]
                   asComponentDescription:desc
                                     name:name
                                  version:g_descriptor->version];
}

