#ifndef AU_SHIM_TYPES_H
#define AU_SHIM_TYPES_H

#include <stdint.h>

// Shared C types for the Rust ↔ ObjC/C boundary.
// Used by both au_shim.m (AU v3) and au_v2_shim.c (AU v2).

// SysEx byte-pool capacity, mirrored from `truce_core::SYSEX_POOL_PREALLOC`.
// Defined here so the Swift template (which can't import Rust consts)
// can size its per-render output scratch buffer without re-declaring
// the magic number. Keep in sync with the Rust constant.
#define TRUCE_SYSEX_POOL_PREALLOC (128 * 1024)

// AU shim ABI version word. `AuCallbacks::abi_version` (its first
// field, at a fixed offset that must never move) reports which version
// the plugin was built against, so a v3 appex generated by a *newer*
// cargo-truce can tell whether an *older* plugin binary actually
// provides the tail callbacks it wants to call (UMP output, legacy
// state) before invoking them. The `AuCallbacks` / `AuPluginDescriptor`
// tails are append-only; the version says how far the tails extend.
//
// The high three bytes are a magic tag ('TAu\0'), the low byte the
// version, so a reader can tell a real version word from garbage: a
// pre-2.0 binary has the `create` function pointer at offset 0, and a
// bare small-integer scheme would read its low bits as a "version"
// that passes ordering gates. Readers must check the magic before
// trusting the version byte. (The versioned registration symbol -
// `truce_au_register_v2` - only fails mismatched staticlib/shim
// links within one binary; the AU v3 appex binds the framework
// through `g_callbacks` / `g_descriptor` / `truce_au_init`, whose
// names predate 2.0, so cross-binary skew is caught only by this
// word at runtime.)
//
// Bump the low byte whenever a field is appended - or an unreleased
// tail callback changes signature - and mirror it in
// `truce_au::ffi::TRUCE_AU_ABI_VERSION` (a lockstep test guards it).
// v2: `output_ump_count` / `output_ump_at` gained the `protocol`
// argument; an appex must not drain a v1 binary through them.
// v3: appended `latency_samples` / `tail_samples`; an appex must not
// query them on a pre-v3 binary (the pointers would be past its tail).
// v4: appended `set_render_mode`; a shim must not push a render-mode
// change into a pre-v4 binary (the pointer would be past its tail).
// v5: appended `param_parse_value`; a shim must not call it on a pre-v5
// binary (the pointer would be past its tail).
#define TRUCE_AU_ABI_MAGIC_MASK 0xFFFFFF00u
#define TRUCE_AU_ABI_MAGIC 0x54417500u
#define TRUCE_AU_ABI_VERSION 0x54417505u

typedef struct {
    uint8_t component_type[4];
    uint8_t component_subtype[4];
    uint8_t component_manufacturer[4];
    const char *name;
    const char *vendor;
    uint32_t version;
    uint32_t num_inputs;
    uint32_t num_outputs;
    /* Param ID flagged as IS_BYPASS, or UINT32_MAX for "no bypass param".
     * The shim routes kAudioUnitProperty_BypassEffect get/set through
     * this ID so the host's master-bypass UI tracks the param value. */
    uint32_t bypass_param_id;
    /* 1 if the plugin emits MIDI to the host. The v2 shim gates the
     * MIDIOutputCallback property and the v3 shim gates
     * `MIDIOutputNames` on this, so a pure audio effect doesn't show
     * a phantom "MIDI Out" port in the host UI. */
    int32_t has_midi_output;
    /* 1 if the plugin accepts MIDI input. The v2 shim gates its
     * `MusicDeviceMIDIEvent` handler lookup on this - decoupled from
     * the `aumu` component type so an `aumf` MusicEffect (audio effect
     * that opts into MIDI input) is also handed events. */
    int32_t accepts_midi_in;
    /* Number of MIDI input / output ports. AU v2 is single-stream, so it
     * ignores these (one port). AU v3 uses `midi_output_ports` to size
     * `MIDIOutputNames`; multi-port MIDI input is not wired yet, so the
     * input count is informational for now. */
    uint32_t midi_input_ports;
    uint32_t midi_output_ports;
    /* 1 if the plugin's MIDI input port is MIDI 2.0 dialect (`midi2 =
     * true` in truce.toml). The AU v3 appex declares
     * `audioUnitMIDIProtocol` = 2.0 when set so the host delivers native
     * UMP 2.0 input; otherwise it declares 1.0 and the host down-converts
     * input. AU v2 ignores it (single-stream MIDI 1.0). */
    int32_t midi2_input;
    /* 1 if the plugin's MIDI output port is MIDI 2.0 dialect. The AU v3
     * appex emits the plugin's output as a pure UMP 2.0 stream via
     * `midiOutputEventListBlock` when set - independent of the input
     * protocol - so per-note output (PerNotePitchBend / PerNoteCC) isn't
     * down-converted onto one channel. Independent of `midi2_input` (a
     * 1.0 -> 2.0 promoter is 1.0 in, 2.0 out; AU v3 input and output are
     * separate self-describing streams). AU v2 ignores it. */
    int32_t midi2_output;
    /* Supported (in, out) channel-count configs from `bus_layouts()`.
     * `layout_in_channels[i]` / `layout_out_channels[i]` are the main-bus
     * channel counts of layout `i`; both arrays are `num_layouts` long.
     * AU v2 reports them through `kAudioUnitProperty_SupportedNumChannels`
     * (one `AUChannelInfo` each) and AU v3 through `channelCapabilities`,
     * so a host can pick any declared layout. `num_layouts == 0` means the
     * single `(num_inputs, num_outputs)` pair is the only config (older
     * registration path); append-only, so an out-of-date shim ignores it. */
    const int16_t *layout_in_channels;
    const int16_t *layout_out_channels;
    uint32_t num_layouts;
    /* Channel count of the sidechain input bus (the second input bus), or
     * 0 when the plugin declares no sidechain. Non-zero makes the v2 shim
     * expose a second kAudioUnitScope_Input element the host routes a
     * separate source to; `num_inputs` is the main input bus (element 0).
     * Append-only, so an out-of-date shim ignores it. */
    uint32_t sidechain_in_channels;
} AuPluginDescriptor;

typedef struct {
    uint32_t id;
    const char *name;
    double min;
    double max;
    double default_value;
    uint32_t step_count;
    const char *unit;
    const char *group;
    /* Default host MIDI-learn binding, surfaced through
     * kAudioUnitProperty_AllParameterMIDIMappings. midi_status is the
     * MIDI status high-nibble (0xB0 control change, 0xE0 pitch bend,
     * 0xD0 channel pressure, 0xC0 program change) or 0 when the param
     * declares no binding. midi_data1 is the CC number (0 for non-CC
     * sources). midi_channel is the wire channel 0..=15, or -1 for any
     * channel. */
    uint8_t midi_status;
    uint8_t midi_data1;
    int16_t midi_channel;
} AuParamDescriptor;

typedef struct {
    uint32_t sample_offset;
    uint8_t status;
    uint8_t data1;
    uint8_t data2;
    /* MIDI cable / port. Output: the AU v3 appex passes this as the
     * `cable` to `midiOutputEventBlock` (0 on AU v2, which is single
     * stream). Input: currently always 0 (multi-cable input unwired). */
    uint8_t port;
} AuMidiEvent;

/* Universal MIDI Packet container - carries MIDI 2.0 channel-voice
 * messages (64-bit UMPs) and forward-compat slots for SysEx-8 / data
 * (128-bit UMPs). Used only by the AU v3 path; AU v2 hosts deliver
 * legacy 3-byte MIDI 1.0 via `AuMidiEvent` and pass `NULL`/`0` for the
 * MIDI 2.0 array. The MSB of `words[0]` carries the UMP message type
 * nibble (0x2_ = MIDI 1.0 CV, 0x4_ = MIDI 2.0 CV, …) - see the M2-104
 * spec, §2.1.4. */
typedef struct {
    uint32_t sample_offset;
    uint32_t words[4];
} AuMidi2Event;

/* Plugin -> host UMP output event (AU v3). The v3 appex drains these
 * via `output_ump_count` / `output_ump_at` (passing the host's
 * protocol) and builds a `MIDIEventList` for
 * `midiOutputEventListBlock`. `word_count` is 1 (MT 0x2 = MIDI 1.0 CV,
 * 1.0-protocol streams) or 2 (MT 0x4 = MIDI 2.0 CV in 2.0 streams, and
 * MT 0x3 SysEx-7 in either); only that many `words` are valid. `cable`
 * is the MIDI output port. */
typedef struct {
    uint32_t sample_offset;
    uint8_t cable;
    uint8_t word_count;
    uint8_t _reserved[2];
    uint32_t words[4];
} AuUmpEvent;

/* Host-side parameter automation event. The AU v3 shim decodes
 * AURenderEvent.parameter / .parameterRamp entries into this shape
 * (one row per host event), with `sample_offset` relative to the
 * start of the current render block. The Rust process callback
 * converts each row into an `EventBody::ParamChange` with the same
 * offset so the per-sample chunker splits the audio block at each
 * automation point. AU v2 has no per-sample parameter automation
 * in its API (`AudioUnitSetParameter` carries no sample-offset), so
 * the v2 shim passes `NULL`/`0` for this array. */
typedef struct {
    uint32_t sample_offset;
    uint32_t param_id;
    float value;
} AuParamEvent;

/* Transport snapshot filled by the AU v2 / v3 shim from
 * HostCallbackInfo (v2) or AUAudioUnit.musicalContextBlock +
 * transportStateBlock (v3). Fields default to 0 / false when the host
 * does not report them. */
typedef struct {
    int32_t valid;          /* 1 if any host callback responded */
    int32_t playing;
    int32_t recording;
    int32_t loop_active;
    int32_t time_sig_num;   /* 0 = host did not report */
    int32_t time_sig_den;   /* 0 = host did not report */
    double tempo;           /* 0 = host did not report */
    double position_samples;
    double position_beats;  /* 0 = host did not report */
    double bar_start_beats;
    double loop_start_beats;
    double loop_end_beats;
} AuTransportSnapshot;

typedef struct {
    /* ABI version the plugin was built against (TRUCE_AU_ABI_VERSION).
     * MUST stay the first field so a shim/appex of any version can
     * read it at offset 0 before touching the rest of the struct.
     * Consumers gate the append-only tail callbacks on it. */
    uint32_t abi_version;
    void *(*create)(void);
    void (*destroy)(void *ctx);
    void (*reset)(void *ctx, double sample_rate, uint32_t max_frames);
    /* `transport` may be NULL when the host did not provide any transport
     * info for this block. */
    void (*process)(void *ctx,
                    const float **inputs, float **outputs,
                    uint32_t num_input_channels, uint32_t num_output_channels,
                    uint32_t num_frames,
                    const AuMidiEvent *events, uint32_t num_events,
                    const AuMidi2Event *events2, uint32_t num_events2,
                    const AuParamEvent *param_events, uint32_t num_param_events,
                    const AuTransportSnapshot *transport);
    uint32_t (*param_count)(void *ctx);
    /* Per-param descriptors are read from `g_param_descriptors`
     * rather than via callback (set once at registration). */
    double (*param_get_value)(void *ctx, uint32_t id);
    void (*param_set_value)(void *ctx, uint32_t id, double value);
    uint32_t (*param_format_value)(void *ctx, uint32_t id, double value,
                                    char *out, uint32_t out_len);
    void (*state_save)(void *ctx, uint8_t **out_data, uint32_t *out_len);
    void (*state_load)(void *ctx, const uint8_t *data, uint32_t len);
    void (*state_free)(uint8_t *data, uint32_t len);
    /* Plugin → host MIDI output. The Rust side filters its event
     * queue to events that fit in 3-byte MIDI 1.0 packets so the
     * shim can iterate `0..count` without checking for skipped
     * slots. Mirrors the input direction's `AuMidiEvent` shape. */
    uint32_t (*output_event_count)(void *ctx);
    void (*output_event_at)(void *ctx, uint32_t index, AuMidiEvent *out);
    /* SysEx output. The Rust side iterates over EventBody::SysEx
     * variants in its output_events queue; the shim drains via
     * `output_sysex_count` + `output_sysex_at`, fragments each
     * payload into UMP SysEx-8 packets, and emits through the
     * AU v3 host's `midiOutputEventListBlock` (or - on older AU v2
     * hosts that don't expose that block - the legacy
     * `midiOutputCallback` with framed 0xF0/0xF7 bytestream).
     *
     * `out_bytes` points into the plugin's EventList SysEx pool;
     * valid until the next process() call clears the pool, which
     * is after the shim has copied / emitted. */
    uint32_t (*output_sysex_count)(void *ctx);
    void (*output_sysex_at)(void *ctx, uint32_t index,
                            uint32_t *out_delta_frames,
                            const uint8_t **out_bytes,
                            uint32_t *out_len);
    /* GUI */
    int32_t (*gui_has_editor)(void *ctx);
    void (*gui_get_size)(void *ctx, uint32_t *w, uint32_t *h);
    void (*gui_open)(void *ctx, void *parent);
    void (*gui_close)(void *ctx);
    /* Whether the editor advertised `can_resize() == true`. The AU
     * v3 Swift shim consults this in `viewDidLayoutSubviews` to
     * decide whether to propagate the host's bounds change to the
     * editor via `gui_set_size`. AU v2 hosts don't have a
     * matching mechanism today; that wiring is tracked
     * separately. */
    int32_t (*gui_can_resize)(void *ctx);
    /* Host-driven set_size. The Swift v3 shim calls this when the
     * host's container view changes our bounds (drag-resize). w/h
     * are in logical points. */
    void (*gui_set_size)(void *ctx, uint32_t w, uint32_t h);
    /* Factory presets, backing kAudioUnitProperty_FactoryPresets.
     * Sourced from the .trucepreset files `cargo truce install`
     * bundles into the component's Contents/Resources/Presets/.
     * `count == 0` means none shipped; the shim then reports the
     * property as invalid (matching AUs without factory presets).
     * `factory_preset_name` returns a UTF-8 string owned by the
     * Rust side, valid for the process lifetime.
     *
     * Fields are append-only past this point: the v3 appex shim
     * can be compiled against a newer header than the plugin
     * binary's struct, so earlier offsets must never shift. */
    uint32_t (*factory_preset_count)(void *ctx);
    const char *(*factory_preset_name)(void *ctx, uint32_t index);
    /* Load the index-th factory preset into the plugin - the same
     * apply path as state_load. Returns 1 on success. */
    int32_t (*factory_preset_load)(void *ctx, uint32_t index);
    /* Host → plugin SysEx input (AU v2 `MusicDeviceSysEx`). The shim
     * strips the 0xF0/0xF7 framing and passes the inner bytes; the
     * Rust side copies into its EventList SysEx pool. `sample_offset`
     * is block-relative (0 for AU v2's untimed SysEx API). AU v3
     * delivers SysEx in-line as UMP SysEx-7/8 through the `events2`
     * slice of `process` and does not use this callback. */
    void (*push_sysex_input)(void *ctx, uint32_t sample_offset,
                             const uint8_t *bytes, uint32_t len);
    /* UMP channel-voice output for AU v3's `MIDIEventList` block. The
     * appex passes `protocol` (1 = MIDI 1.0, 2 = MIDI 2.0, from the
     * host's `hostMIDIProtocol`) and the Rust side encodes a *pure*
     * stream in it - all MT 0x2 packets for 1.0, all MT 0x4 for 2.0
     * (events convert across dialects as needed; SysEx-7 MT 0x3 is
     * legal in both). The UMP spec forbids mixing 1.0 and 2.0
     * channel-voice packets in one protocol stream. The count depends
     * on the protocol (a 2.0-only event may have no 1.0 form), so both
     * calls take it. Appended here (not next to the other output_*
     * callbacks) to honor the append-only rule above - inserting
     * mid-struct would shift every later offset. */
    uint32_t (*output_ump_count)(void *ctx, uint32_t protocol);
    void (*output_ump_at)(void *ctx, uint32_t protocol, uint32_t index, AuUmpEvent *out);
    /* Legacy foreign-state probing (state migration). When a host's
     * ClassInfo dictionary carries no `truce_state` entry, the shim
     * asks for the container keys a pre-truce build stored its state
     * under (`[plugin.legacy_state]` `au_keys` in truce.toml) and
     * feeds the first present key's bytes to `state_load_foreign`,
     * which routes them to the plugin's `migrate_state` hook.
     * `legacy_state_key_at` returns UTF-8 owned by the Rust side,
     * valid for the instance lifetime. `state_load_foreign` returns 1
     * when the plugin accepted (translated) the bytes. */
    uint32_t (*legacy_state_key_count)(void *ctx);
    const char *(*legacy_state_key_at)(void *ctx, uint32_t index);
    int32_t (*state_load_foreign)(void *ctx, const char *key,
                                  const uint8_t *data, uint32_t len);
    /* Plugin delay compensation. Both return the plugin's current
     * latency / release-tail length in *samples*; the shim divides by
     * the sample rate to report seconds through
     * kAudioUnitProperty_Latency / kAudioUnitProperty_TailTime (v2) and
     * AUAudioUnit.latency / .tailTime (v3). Values track the plugin's
     * `latency()` / `tail()` and are refreshed on reset and every
     * process block; a host reads them after initialization, so a
     * static-latency plugin reports correctly. Appended per the
     * append-only rule; a pre-v3 binary lacks them (gate on
     * abi_version). */
    uint32_t (*latency_samples)(void *ctx);
    uint32_t (*tail_samples)(void *ctx);
    /* Host -> plugin render-mode signal. The host sets AU offline
     * rendering (`kAudioUnitProperty_OfflineRender` on v2,
     * `AUAudioUnit.isRenderingOffline` on v3); the shim forwards it here
     * as a `ProcessMode` discriminant (0 realtime, 1 buffered, 2
     * offline) so the plugin can raise quality / relax realtime
     * discipline during a bounce. The Rust side stashes it in an atomic
     * that `reset` and every `process` block read. Appended per the
     * append-only rule; gate on abi_version (>= v4) before calling. */
    void (*set_render_mode)(void *ctx, uint32_t mode);
    /* Host text entry -> plain param value. The shim converts the host's
     * CFString (v2 `kAudioUnitProperty_ParameterValueFromString`, v3
     * `implementorValueFromStringCallback`) to UTF-8 and calls this;
     * returns 1 and writes `out_plain` on a successful parse, 0 when the
     * text isn't valid for the param (the shim then leaves the value
     * unchanged). Appended per the append-only rule; gate on abi_version
     * (>= v5) before calling. */
    int32_t (*param_parse_value)(void *ctx, uint32_t id, const char *text,
                                 double *out_plain);
} AuCallbacks;

// Globals shared between v2 and v3 shims.
// Populated by truce_au_register_v2() (called from the constructor).
extern const AuPluginDescriptor *g_descriptor;
extern const AuCallbacks *g_callbacks;
extern const AuParamDescriptor *g_param_descriptors;
extern uint32_t g_num_params;

// Rust-side init function - generated by export_au! macro.
extern void truce_au_init(void);

// FourCharCode helper (big-endian UInt32 from byte array).
#define FOURCC(b) (((uint32_t)(b)[0] << 24) | ((uint32_t)(b)[1] << 16) | \
                   ((uint32_t)(b)[2] << 8)  | (uint32_t)(b)[3])

#endif // AU_SHIM_TYPES_H
