#ifndef AU_SHIM_TYPES_H
#define AU_SHIM_TYPES_H

#include <stdint.h>

// Shared C types for the Rust ↔ ObjC/C boundary.
// Used by both au_shim.m (AU v3) and au_v2_shim.c (AU v2).

typedef struct {
    uint8_t component_type[4];
    uint8_t component_subtype[4];
    uint8_t component_manufacturer[4];
    const char *name;
    const char *vendor;
    uint32_t version;
    uint32_t num_inputs;
    uint32_t num_outputs;
} AuPluginDescriptor;

typedef struct {
    uint32_t id;
    const char *name;
    double min;
    double max;
    double default_value;
    uint32_t step_count;
    const char *unit;
    const char *group;
} AuParamDescriptor;

typedef struct {
    uint32_t sample_offset;
    uint8_t status;
    uint8_t data1;
    uint8_t data2;
    uint8_t _pad;
} AuMidiEvent;

/* Transport snapshot filled by the AU v2 / v3 shim from
 * HostCallbackInfo (v2) or AUAudioUnit.musicalContextBlock +
 * transportStateBlock (v3). Fields default to 0 / false when the host
 * does not report them. */
typedef struct {
    int32_t valid;          /* 1 if any host callback responded */
    int32_t playing;
    int32_t recording;
    int32_t loop_active;
    int32_t time_sig_num;   /* 0 = host did not report */
    int32_t time_sig_den;   /* 0 = host did not report */
    double tempo;           /* 0 = host did not report */
    double position_samples;
    double position_beats;  /* 0 = host did not report */
    double bar_start_beats;
    double loop_start_beats;
    double loop_end_beats;
} AuTransportSnapshot;

typedef struct {
    void *(*create)(void);
    void (*destroy)(void *ctx);
    void (*reset)(void *ctx, double sample_rate, uint32_t max_frames);
    /* `transport` may be NULL when the host did not provide any transport
     * info for this block. */
    void (*process)(void *ctx,
                    const float **inputs, float **outputs,
                    uint32_t num_input_channels, uint32_t num_output_channels,
                    uint32_t num_frames,
                    const AuMidiEvent *events, uint32_t num_events,
                    const AuTransportSnapshot *transport);
    uint32_t (*param_count)(void *ctx);
    void (*param_get_descriptor)(void *ctx, uint32_t index, AuParamDescriptor *out);
    double (*param_get_value)(void *ctx, uint32_t id);
    void (*param_set_value)(void *ctx, uint32_t id, double value);
    uint32_t (*param_format_value)(void *ctx, uint32_t id, double value,
                                    char *out, uint32_t out_len);
    void (*state_save)(void *ctx, uint8_t **out_data, uint32_t *out_len);
    void (*state_load)(void *ctx, const uint8_t *data, uint32_t len);
    void (*state_free)(uint8_t *data, uint32_t len);
    /* GUI */
    int32_t (*gui_has_editor)(void *ctx);
    void (*gui_get_size)(void *ctx, uint32_t *w, uint32_t *h);
    void (*gui_open)(void *ctx, void *parent);
    void (*gui_close)(void *ctx);
} AuCallbacks;

// Globals shared between v2 and v3 shims.
// Populated by truce_au_register() (called from the constructor).
extern const AuPluginDescriptor *g_descriptor;
extern const AuCallbacks *g_callbacks;
extern const AuParamDescriptor *g_param_descriptors;
extern uint32_t g_num_params;

// Rust-side init function — generated by export_au! macro.
extern void truce_au_init(void);

// FourCharCode helper (big-endian UInt32 from byte array).
#define FOURCC(b) (((uint32_t)(b)[0] << 24) | ((uint32_t)(b)[1] << 16) | \
                   ((uint32_t)(b)[2] << 8)  | (uint32_t)(b)[3])

#endif // AU_SHIM_TYPES_H
