use truce::prelude::*;
use truce_gui::layout::{GridLayout, knob, widgets};

// --- Parameters ---

use TransposeParamsParamId as P;

#[derive(Params)]
pub struct TransposeParams {
    #[param(name = "Semitones", short_name = "Semi",
            range = "discrete(-12, 12)", unit = "st")]
    pub semitones: FloatParam,

    #[param(name = "Octave", short_name = "Oct",
            range = "discrete(-3, 3)")]
    pub octave: FloatParam,
}

// new() and Default are generated by #[derive(Params)] + #[param(...)]

// --- Plugin ---

pub struct Transpose {
    pub params: std::sync::Arc<TransposeParams>,
    /// Maps input note -> output note that was actually sent.
    /// Used to send correct NoteOff even if shift changes mid-hold.
    active_notes: [Option<u8>; 128],
}

impl Transpose {
    pub fn new(params: std::sync::Arc<TransposeParams>) -> Self {
        Self {
            params,
            active_notes: [None; 128],
        }
    }
}

impl PluginLogic for Transpose {
    fn reset(&mut self, sample_rate: f64, _max_block_size: usize) {
        self.params.set_sample_rate(sample_rate);
        self.params.snap_smoothers();
    }

    fn process(&mut self, _buffer: &mut AudioBuffer, events: &EventList, context: &mut ProcessContext) -> ProcessStatus {
        let semitones = self.params.semitones.value() as i16;
        let octave = self.params.octave.value() as i16;
        let shift = semitones + octave * 12;

        for event in events.iter() {
            match &event.body {
                EventBody::NoteOn { channel, note, velocity } => {
                    let transposed = (*note as i16 + shift).clamp(0, 127) as u8;
                    self.active_notes[*note as usize] = Some(transposed);
                    context.output_events.push(Event {
                        sample_offset: event.sample_offset,
                        body: EventBody::NoteOn {
                            channel: *channel,
                            note: transposed,
                            velocity: *velocity,
                        },
                    });
                }
                EventBody::NoteOff { channel, note, velocity } => {
                    // Use the pitch that was actually sent, not current shift
                    let output_note = self.active_notes[*note as usize]
                        .take()
                        .unwrap_or((*note as i16 + shift).clamp(0, 127) as u8);
                    context.output_events.push(Event {
                        sample_offset: event.sample_offset,
                        body: EventBody::NoteOff {
                            channel: *channel,
                            note: output_note,
                            velocity: *velocity,
                        },
                    });
                }
                _ => {}
            }
        }

        ProcessStatus::Normal
    }

    fn layout(&self) -> truce_gui::layout::GridLayout {
        GridLayout::build("TRANSPOSE", "V0.1", 2, 80.0, vec![widgets(vec![
            knob(P::Semitones, "Semitones"),
            knob(P::Octave, "Octave"),
        ])])
    }
}

truce::plugin! {
    logic: Transpose,
    params: TransposeParams,
}

// --- Tests ---

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn transpose_up_octave() {
        let params = std::sync::Arc::new(TransposeParams::new());
        let mut plugin = Transpose::new(std::sync::Arc::clone(&params));
        plugin.params.octave.set_value(1.0);
        plugin.reset(44100.0, 512);

        let input = vec![vec![0.0f32; 512]; 2];
        let input_refs: Vec<&[f32]> = input.iter().map(|v| v.as_slice()).collect();
        let mut output = vec![vec![0.0f32; 512]; 2];
        let mut output_refs: Vec<&mut [f32]> = output.iter_mut().map(|v| v.as_mut_slice()).collect();

        let mut buffer = unsafe { AudioBuffer::from_slices(&input_refs, &mut output_refs, 512) };

        let mut events = EventList::new();
        events.push(Event {
            sample_offset: 0,
            body: EventBody::NoteOn { channel: 0, note: 60, velocity: 0.8 },
        });

        let transport = TransportInfo::default();
        let mut output_events = EventList::new();
        let mut context = ProcessContext::new(&transport, 44100.0, 512, &mut output_events);

        plugin.process(&mut buffer, &events, &mut context);

        assert_eq!(output_events.len(), 1);
        match &output_events.get(0).unwrap().body {
            EventBody::NoteOn { note, .. } => assert_eq!(*note, 72), // C4 + 12 = C5
            _ => panic!("Expected NoteOn"),
        }
    }

    #[test]
    fn gui_snapshot() {
        let params = std::sync::Arc::new(TransposeParams::new());
        let transpose = Transpose::new(std::sync::Arc::clone(&params));
        let layout = transpose.layout();
        truce_test::assert_gui_snapshot_grid::<TransposeParams>(
            "transpose_default", params, layout, 0,
        );
    }
}
